version: '3'
services:
  ft_stunnel:
    build: ./1_stunnel
    restart: unless-stopped
    hostname: "ft_stunnel"
    container_name: "ft_stunnel"
    dns: 10.99.7.248
    extra_hosts:
      - "ft_unbound:10.99.7.248"
      - "ft_dnsmasq:10.99.7.249"
      - "ft_api_admin:10.99.7.250"
      - "ft_hitch:10.99.7.251"
      - "ft_varnish:10.99.7.252"
      - "ft_stunnel:10.99.7.253"
    volumes:
      - ./1_stunnel/resolv.conf:/etc/resolv.conf
      - ./1_stunnel/conf.d:/etc/stunnel/conf.d
      - ./1_stunnel/stunnel.conf:/etc/stunnel/stunnel.conf
    networks:
      ft_network:
        ipv4_address: 10.99.7.253
    command: ["./client.sh"]

  ft_varnish:  
    build: ./2_varnish
    restart: unless-stopped
    hostname: "ft_varnish"
    container_name: "ft_varnish"
    dns: 10.99.7.249
    extra_hosts:
      - "ft_unbound:10.99.7.248"
      - "ft_dnsmasq:10.99.7.249"
      - "ft_api_admin:10.99.7.250"
      - "ft_hitch:10.99.7.251"
      - "ft_varnish:10.99.7.252"
      - "ft_stunnel:10.99.7.253"
    networks:
      ft_network:
        ipv4_address: 10.99.7.252
    links:
      - "ft_stunnel"
    volumes:
      - ./2_varnish/etc/varnish:/etc/varnish
      - ./2_varnish/resolv.conf:/etc/resolv.conf
    depends_on:
      - ft_stunnel
    command: ["/run.sh"]

  ft_hitch:
    build: ./3_hitch  
    restart: unless-stopped
    hostname: "ft_hitch"
    container_name: "ft_hitch"
    dns: 10.99.7.249
    extra_hosts:
      - "ft_unbound:10.99.7.248"
      - "ft_dnsmasq:10.99.7.249"
      - "ft_api_admin:10.99.7.250"
      - "ft_hitch:10.99.7.251"
      - "ft_varnish:10.99.7.252"
      - "ft_stunnel:10.99.7.253"
    networks:
      ft_network:
        ipv4_address: 10.99.7.251
    links:
      - "ft_varnish"
    volumes:
      - ./3_hitch/etc/ssl/hitch:/etc/ssl/hitch
      - ./3_hitch/resolv.conf:/etc/resolv.conf
    env_file:
      - ./3_hitch/env_hitch
    depends_on:
      - ft_varnish

  ft_api_admin:
    build: ./4_api_admin
    restart: unless-stopped
    hostname: "ft_api_admin"
    container_name: "ft_api_admin"
    dns: 10.99.7.249
    extra_hosts:
      - "ft_unbound:10.99.7.248"
      - "ft_dnsmasq:10.99.7.249"
      - "ft_api_admin:10.99.7.250"
      - "ft_hitch:10.99.7.251"
      - "ft_varnish:10.99.7.252"
      - "ft_stunnel:10.99.7.253"
    volumes:
      - ./4_api_admin/resolv.conf:/etc/resolv.conf
    networks:
      ft_network:
        ipv4_address: 10.99.7.250 

  ft_dnsmasq:
    build: ./6_dnsmasq
    restart: unless-stopped
    hostname: "ft_dnsmasq"
    container_name: "ft_dnsmasq"
    dns: 10.99.7.249
    extra_hosts:
      - "ft_unbound:10.99.7.248"
      - "ft_dnsmasq:10.99.7.249"
      - "ft_api_admin:10.99.7.250"
      - "ft_hitch:10.99.7.251"
      - "ft_varnish:10.99.7.252"
      - "ft_stunnel:10.99.7.253"
    volumes:
      - ./6_dnsmasq/dnsmasq.d:/etc/dnsmasq.d
      - ./6_dnsmasq/resolv.conf:/etc/resolv.conf
    networks:
      ft_network:
        ipv4_address: 10.99.7.249 
    command: ["/run.sh"]

  ft_unbound:
    build: ./7_unbound
    restart: unless-stopped
    hostname: "ft_unbound"
    container_name: "ft_unbound"
    dns: 10.99.7.248
    extra_hosts:
      - "ft_unbound:10.99.7.248"
      - "ft_dnsmasq:10.99.7.249"
      - "ft_api_admin:10.99.7.250"
      - "ft_hitch:10.99.7.251"
      - "ft_varnish:10.99.7.252"
      - "ft_stunnel:10.99.7.253"
    volumes:
      - ./7_unbound/unbound.conf:/etc/unbound/unbound.conf
      - ./7_unbound/resolv.conf:/etc/resolv.conf
    networks:
      ft_network:
        ipv4_address: 10.99.7.248
    command: ["/run.sh"]

networks:
  ft_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.99.0.0/21
    driver_opts:
      com.docker.network.bridge.name: ft_bridge
